services:
  - type: web
    name: clash-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: MONGO_URI
        sync: false
      - key: FANCLASH_API
        value: https://clash-api-m5mr.onrender.com/api
      - key: PYTHON_VERSION
        value: 3.11.0